### ISSUE TITLE
Warning: Use of undefined constant UPLOADS in /acf-extensions/fields/class-acf-field-instagram_post.php on line 113

### ISSUE THREAD

**Issue by bonakor** [wearemetabolism/acf-extensions#3]
Hi,
I have this warning in WP : Warning: Use of undefined constant UPLOADS - assumed 'UPLOADS' (this will throw an Error in a future version of PHP) in /plugins/acf-extensions/fields/class-acf-field-instagram_post.php on line 113

If I add a UPLOADS definition in my WP_config, all of my images have a 404 issue, because my ABSPATH is already defined.

If I remove my ABSPATH, everything breaks. 

Is there anyway I could edit the line 113 to avoid this warning, please?

Thank you!

**Comment by jerome-barbato** [comment]
Hello @bonakor , I've also seen this issue yesterday, I just released a new version.
Could you try it and send me your feedback ?
thank you

**Comment by bonakor** [comment]
It seems good, yes. Thank you
