### ISSUE TITLE
Going from 1.1.12 to 1.3.2, bug with component

### ISSUE THREAD

**Issue by bonakor** [wearemetabolism/acf-extensions#4]
On my website, I use components.

When I update from 1.1.12 to a more recent version, I hve this weird issue:
The whole component displays and not just the title:
![image](https://user-images.githubusercontent.com/6813789/214849469-b99191a3-7e23-4cf8-94a2-f92b6791df07.png)

Could it come from the component preview?

**Comment by jerome-barbato** [comment]
Hello @bonakor, it seems to be a screenshot from the backoffice right ? Are you using the dynamic select ?
Could you send me some components json config files to test it?

**Comment by bonakor** [comment]
Hi,
No, it's a component field. Yes, I can send you the json config file. Where can I send it?

**Comment by jerome-barbato** [comment]
@bonakor please send at jerome[a]akhela.fr

**Comment by jerome-barbato** [comment]
Hello @bonakor I didn't receive anything, did you sent something ?

**Comment by bonakor** [comment]
Hi, sorry, not yet. Spent the last few days away from keyboard. Tomorrow I will !

**Comment by jerome-barbato** [comment]
issued fixed !
